### ISSUE TITLE
New major version (v1) of tusd

### ISSUE THREAD

**Issue by Acconut** [tus/tusd#212]
In the last three years tusd has been released under the version v0 and avoided backwards-compatibility breaking changes. However, it is also getting more obvious that we have accumulated technical debt over the years which we cannot get rid of without a major release. This issue tracks a list of ideas what we could change in a future tusd v1:

Before release:
- [x] Drop support for older versions of Go
  - [x] Drop SubTest shim: https://github.com/tus/tusd/blob/master/subtest_test.go
  - [x] Use context package from stdlib: https://github.com/tus/tusd/pull/211
- [x] Build binary releases with Go 1.13 on Linux (with -trimpath)
- [x] Remove DataStore option from configuration in favor of StoreComposer
- [x] Do upload operations (GetInfo, WriteChunk, etc) based on an upload handle struct instead of a file ID (this would allow information from GetInfo to be cached more efficiently)
  - [x] Convert ConcatUploads method
  - [x] Optimize S3 uploads
- [x] Separate locker and data stores into own interfaces
- [x] Drop the consullocker package
- [x] Drop the limitedstore package due to its design flaws
- [x] Move the etcd3locker into separate repository (https://github.com/tus/tusd-etcd3-locker)
- [x] Remove the `.bin` file suffix (see https://github.com/tus/tusd/issues/210)
- [x] Consider moving tusd server into own subdirectory
- [x] Move library packages into `pkg` subfolder (or similar)
- [x] Consider accepting URLs without trailing slashes (i.e `http://localhost:1080/files/` and `http://localhost:1080/files`)
- [x] Add dedicated HookInfo structs with HTTP request data (see https://github.com/tus/tusd/pull/278)
- [x] Add information about stored file to hooks/FileInfo
- [x] Declare dependencies using new Go module system
- [x] Remove dots from folder names, e.g. `.scripts` and `.hooks`
- [x] Use Travis CI for Windows testing
- [x] Remove deprecated memorylocker.NewMemoryLocker function
- [x] Add context to DataStore API functions (see https://github.com/tus/tusd/issues/288)
  - [x] Use context properly in S3Store
- [x] Print tus extension on startup instead of implemented interfaces
- [x] Simplify CLI check (see https://github.com/tus/tusd/issues/229)
- [x] Update `docs/hooks.md`

After release possible:
- [x] Move content from README into proper `docs` folder
- [x] Start prefixing git tags with `v`, e.g. `v1.0.0`

Rejected ideas:
- Consider moving more logic from cmd/tusd/cli to internal/ (see https://github.com/golang-standards/project-layout)
- Consider using different storage systems for binary data and upload information (e.g. S3 for binary and etcd for upload information) (this might allow seamless migration between different binary data stores, e.g. switching buckets)
- Use different command line flags for defining storage and locker, e.g. `tusd --storage s3://my-bucket.com/uploads?acl=private --locker file:///srv/shared/locks`
- Do not allow downloads while the upload is not finished
- Always require a locker
- Return relative URL in Location header when creating an upload

**Comment by janko** [comment]
> Do not allow downloads while the upload is not finished

Is that the opposite of https://github.com/tus/tusd/issues/13?

**Comment by Acconut** [comment]
>  Is that the opposite of #13?

If we decide to "not allow downloads while the upload is not finished", then yes. However, this list is more a collection of thoughts instead of a define list of changes. There has been too little demand for streamable downloads to justify the high engineering cost that this feature would likely require. Besides that, tusd is focused on accepting uploads and primarily not on providing them to other applications.

Or do you have a use case for #13?

**Comment by janko** [comment]
Thanks for the explanation. I don't have a use case for #13, I'm just trying to replicate tusd behaviour as closely as possible in my Ruby server implementation, and wasn't sure which direction to take here. Since my server implementation is already disallowing downloads of unfinished uploads, I'll just keep the current behaviour 😃

**Comment by Acconut** [comment]
Development for tusd v1 has started in the [v1](https://github.com/tus/tusd/tree/v1) branch.

**Comment by chen-anders** [comment]
> Move the etcd3locker into separate repository

I'm happy to take ownership or help with this effort (much like the DynamoDB locker). Let me know how that sounds.

**Comment by Acconut** [comment]
> I'm happy to take ownership or help with this effort (much like the DynamoDB locker). Let me know how that sounds.

Thank you very much for the offering, it definitely sounds like a good plan. I am currently experimenting with slight modifications to the Go interface for LockerDataStore. Once those changes are finalized, I would adjust etcd3lcoker to the new interface and then we can start moving it into its own repository.

**Comment by dantman** [comment]
> * Drop the consullocker package
> * Move the etcd3locker into separate repository

Does this mean all lockers will be 3rd party packages then?

Related, has no-one implemented a Redis locker? Despite the mention of Redis in https://tus.io/faq.html?

**Comment by Acconut** [comment]
> Does this mean all lockers will be 3rd party packages then?

No, the tusd repository will keep the memorylocker and filelocker packages which offer an in-memory and on-disk locking mechanism.

> Related, has no-one implemented a Redis locker? Despite the mention of Redis in https://tus.io/faq.html?

To my knowledge, no such package has been published. For example, for our use cases, Redis is not needed.

**Comment by Acconut** [comment]
@chen-anders Perfect! I just invited you to the repository.

**Comment by Acconut** [comment]
Closing this issue since v1.0 has been release and all tasks have been completed.
